[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "poker-scraper"
version = "0.1.0"
description = "Poker tournament analytics and scraping system"
readme = "readme.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "flask",
    "pymongo",
    "python-dotenv",
    "requests",
    "pandas",
    "rapidfuzz",
]

authors = [
    { name = "John Fox", email = "jicfox7@gmail.com" }
]

[project.urls]
"Repository" = "https://github.com/yourusername/poker-scraper"

[project.scripts]
poker-scraper = "poker_scraper.app:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
