name: Email Database Backup

on:
  schedule:
    - cron: '45 19 * * 6'  # Every Saturday at 2:45 PM CT (7:45 PM UTC)
  workflow_dispatch:

jobs:
  email-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Hit email backup endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/emailroundbackup)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi
