name: Email Database Backup

on:
  schedule:
    # Fridays between 19–30 at 10:00 PM CT → 3:00 AM UTC Saturday to try and catch last friday of offsuit league season
    - cron: '0 3 19-28 * 5'
  workflow_dispatch:

jobs:
  email-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Hit email backup endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/emailroundbackup)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi
