name: Keep Server Alive

on:
  schedule:
    # Every day between 8 AM and 11 PM CT (using UTC times)
    - cron: '*/15 13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4 * * *'  # every 15 min
  workflow_dispatch:         # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      # Hits the endpoint to keep the cache hydrated and server awake
      - name: Hit Trueskill leaderboard endpoint
        run: |
          # Script logic:
          # 1. Make request to API endpoint
          # 2. Success = HTTP 200 + valid JSON response
          # 3. On failure: wait 45s, retry up to 3 times
          # 4. Failures happen during cold starts when:
          #    - Server returns non-200 (not ready)
          #    - Response isn't valid JSON (partial startup)
          
          API_URL="https://api.johnfoxweb.com/api/leaderboard/trueskill"
          MAX_RETRIES=3
          RETRY_DELAY=45
          TIMEOUT=20
          
          for i in {1..3}; do
            echo "Attempt $i/3: Pinging $API_URL..."
            # Capture both response and status code
            response=$(curl --max-time $TIMEOUT -w "\n%{http_code}" "$API_URL")
            code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | sed '$d')
            
            if [ "$code" -eq 200 ]; then
              echo "✅ Success"
              exit 0
            else
              echo "❌ Failed with status code: $code"
              echo "Response body: $body"
              if [ $i -lt 3 ]; then
                sleep $RETRY_DELAY
              fi
            fi
          done
          
          echo "🚨 All attempts failed."
          exit 1