name: Keep Server Alive

on:
  schedule:
    # Every day between 8 AM and 11 PM CT (using UTC times)
    - cron: '*/20 13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4 * * *'  # 8 AM - 11 PM CT
  workflow_dispatch:         # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep server and caches warm
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/updatecaches)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi
          