name: Keep Server Alive

on:
  schedule:
    # Every day between 8 AM and 11 PM CT (using UTC times)
    - cron: '*/20 13,14,15,16,17,18,19,20,21,22,23,0,1,2,3,4 * * *'  # 8 AM - 11 PM CT
  workflow_dispatch:         # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      #hits the endpoint to keep the cache hydrated and server awake
      - name: Hit Trueskill leaderboard endpoint
        run: |
          curl -X GET https://api.johnfoxweb.com/api/leaderboard/trueskill