name: Refresh Rounds DB

on:
  schedule:
    - cron: '29 7 * * *'   # 2:29 AM CT (7:29 AM UTC)
    - cron: '16 14 * * *'  # 9:16 AM CT (2:16 PM UTC)
    - cron: '11 22 * * *'  # 5:11 PM CT (10:11 PM UTC)
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy Python app to Azure Web App - OffsuitPokerAnalyzer"]
    types:
      - completed

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Conditionally wait 40 seconds if triggered by workflow_run #waiting for server to be ready for endpoint call
        if: github.event_name == 'workflow_run'
        run: sleep 40  # 40 seconds

      - name: Hit refresh rounds DB endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/refreshrounds)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi

      - name: Check name clashes
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/checknameclashes)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi

      - name: Update caches
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/updatecaches)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi
