name: Refresh Legacy Rounds DB

on:
  workflow_dispatch:

jobs:
  refresh-legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Hit refresh legacy rounds DB endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/refreshlegacyrounds)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi
