name: Refresh Rounds DB

on:
  schedule:
    - cron: '29 7 * * *'   # 2:29 AM CT (7:29 AM UTC)
    - cron: '16 14 * * *'  # 9:16 AM CT (2:16 PM UTC)
    - cron: '11 22 * * *'  # 5:11 PM CT (10:11 PM UTC)
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and deploy Python app to Azure Web App - OffsuitPokerAnalyzer"]
    types:
      - completed

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Conditionally wait 80 seconds if triggered by workflow_run #waiting for server to be ready for endpoint call
        if: github.event_name == 'workflow_run'
        run: sleep 80  # 80 seconds

      - name: Hit refresh rounds DB endpoint
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/refreshrounds)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi

      - name: Check name clashes
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ADMIN_AUTH_TOKEN }}" \
            https://api.johnfoxweb.com/api/admin/checknameclashes)
          echo "Status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Request failed"
            exit 1
          fi

      - name: Trigger frontend update
        run: |
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.FRONTEND_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -w "\nStatus: %{http_code}" \
            https://api.github.com/repos/jff97/PokerAnalyzerDisplayWebsite/dispatches \
            -d '{"event_type":"refresh_leaderboards"}')
          echo "Response: $response"
          if [[ $response == *"Status: 204"* ]]; then
            echo "Successfully triggered frontend workflow"
          else
            echo "Failed to trigger frontend workflow"
            exit 1
          fi
